# Generated by Django 2.1.2 on 2018-11-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnistwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='inputImage',
        ),
    ]
