# Generated by Django 2.1.2 on 2018-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnistwebsite', '0002_auto_20181130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimage',
            name='image',
            field=models.CharField(max_length=64),
        ),
    ]
