# Generated by Django 2.1.2 on 2018-12-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnistwebsite', '0006_auto_20181202_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_image', models.CharField(max_length=64)),
            ],
        ),
    ]
