# Generated by Django 2.1.2 on 2018-12-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnistwebsite', '0007_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicted_label',
            name='label',
            field=models.CharField(max_length=8),
        ),
    ]
